

aggregation = {
    'Age': 'first',
    'ALT' : 'max',
    'AST' : 'max',
    'Albumin' : 'min',
    'Bilirubin':'max',
    'CaO2':'min',
    'CentralvenousO2Saturation':'min',
    'Centralvenouspressure':'min',
    'Creatinine' : 'max',
    'Creactiveprotein' : 'max',
    'DiasBP1' : 'min',
    'Fibrinogen':'max',
    'Fio2' : 'max',
    'Haemoglobin' : 'min',
    'Heartrate':'min',
    'INR': 'max',
    'Lactatedehydrogenase':'max',
    'Lymphocytes' : 'mean',
    'MeanBP1': 'min',
    'Neutrophils' : 'mean',
    'PTT' : 'max',
    'PaCO2': 'max',
    'PaO2': 'max',
    'PeripheralO2Saturation': 'max',
    'Platelets': 'min',
    'SysBP1' : 'min',
    'PvCO2': 'max',
    'Sao2': 'max',
    'SpontaneousResRate': 'max',
    'Temperature': 'max',
    'Urea' : 'max',
    'WBC' : 'max'
}
